server:
  port: 8085
  servlet:
    context-path: /danzhu/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/danzhu?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


danzhu:
  security:
    jwt-key: zeffonwu
    token-expired-in: 86400000

springfox:
  documentation:
    swagger-ui:
      enabled: true